# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8671b25c38c0903209dffea1a776958845d82129d9e01b4410a5165c9425f7bbd8057c7b97a7403970aee2829291b5b9b24a86dae6caf3016d3bdaea482f2208

test:
  secret_key_base: 4bc6528b840fc815d8d83824aac0b870e4e37db4ef65a94eaaa264a5b002cbae0c8c58d90157aeb5c176e7052171749bc0764bd9878faee0e2371934c648126e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
